version: "3.3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart:
      unless-stopped
    links:
      - "db"
    networks: # Networks to join
      - local
    tty:
      true
networks:
  local:
    driver: bridge